-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-09-19 22:05:14 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE area (
    area_id     NUMBER NOT NULL,
    nombre_area VARCHAR2(60) NOT NULL,
    piso        VARCHAR2(10)
);

ALTER TABLE area ADD CONSTRAINT area_pk PRIMARY KEY ( area_id );

ALTER TABLE area ADD CONSTRAINT area_nombre_area_un UNIQUE ( nombre_area );

CREATE TABLE atencion (
    historia_id     NUMBER NOT NULL,
    atencion_id     NUMBER NOT NULL,
    fecha_hora      DATE NOT NULL,
    tipo_atencion   VARCHAR2(20) NOT NULL,
    motivo_consulta VARCHAR2(300) NOT NULL,
    observaciones   VARCHAR2(1000)
);

ALTER TABLE atencion
    ADD
        CHECK ( tipo_atencion IN ( 'consulta_externa', 'control', 'urgencias' ) );

ALTER TABLE atencion ADD CONSTRAINT atencion_pk PRIMARY KEY ( atencion_id );

CREATE TABLE atiende (
    atencion_atencion_id NUMBER NOT NULL,
    doctor_doctor_id     NUMBER NOT NULL
);

ALTER TABLE atiende ADD CONSTRAINT atiende_pk PRIMARY KEY ( atencion_atencion_id,
                                                            doctor_doctor_id );

CREATE TABLE cama (
    area_id     NUMBER NOT NULL,
    cama_id     NUMBER NOT NULL,
    codigo_cama VARCHAR2(10) NOT NULL,
    estado      VARCHAR2(15) DEFAULT 'libre' NOT NULL
);

ALTER TABLE cama
    ADD
        CHECK ( estado IN ( 'libre', 'mantenimiento', 'ocupada' ) );

ALTER TABLE cama ADD CONSTRAINT cama_pk PRIMARY KEY ( cama_id );

ALTER TABLE cama ADD CONSTRAINT cama_codigo_cama_un UNIQUE ( codigo_cama );

CREATE TABLE diagnostica (
    atencion_atencion_id       NUMBER NOT NULL,
    diagnostico_diagnostico_id NUMBER NOT NULL
);

ALTER TABLE diagnostica ADD CONSTRAINT diagnostica_pk PRIMARY KEY ( atencion_atencion_id,
                                                                    diagnostico_diagnostico_id );

CREATE TABLE diagnostico (
    diagnostico_id     NUMBER NOT NULL,
    codigo_cie         VARCHAR2(10) NOT NULL,
    nombre_diagnostico VARCHAR2(200) NOT NULL,
    descripcion        VARCHAR2(500)
);

ALTER TABLE diagnostico ADD CONSTRAINT diagnostico_pk PRIMARY KEY ( diagnostico_id );

ALTER TABLE diagnostico ADD CONSTRAINT diagnostico_codigo_cie_un UNIQUE ( codigo_cie );

CREATE TABLE doctor (
    doctor_id        NUMBER NOT NULL,
    numero_documento VARCHAR2(20) NOT NULL,
    nombres          VARCHAR2(60) NOT NULL,
    apellidos        VARCHAR2(60) NOT NULL,
    registro_medico  VARCHAR2(30) NOT NULL,
    telefono         VARCHAR2(20),
    especialidad_id  NUMBER NOT NULL
);

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( doctor_id );

ALTER TABLE doctor ADD CONSTRAINT doctor_numero_documento_un UNIQUE ( numero_documento );

ALTER TABLE doctor ADD CONSTRAINT doctor_registro_medico_un UNIQUE ( registro_medico );

CREATE TABLE especialidad (
    especialidad_id     NUMBER NOT NULL,
    nombre_especialidad VARCHAR2(60) NOT NULL,
    descripcion         VARCHAR2(300)
);

ALTER TABLE especialidad ADD CONSTRAINT especialidad_pk PRIMARY KEY ( especialidad_id );

ALTER TABLE especialidad ADD CONSTRAINT especialidad_nombre_un UNIQUE ( nombre_especialidad );

CREATE TABLE examen (
    examen_id             NUMBER NOT NULL,
    nombre_examen         VARCHAR2(120) NOT NULL,
    tipo_examen           VARCHAR2(20) NOT NULL,
    preparacion_requerida VARCHAR2(300)
);

ALTER TABLE examen
    ADD
        CHECK ( tipo_examen IN ( 'imagenologia', 'laboratorio', 'procedimiento' ) );

ALTER TABLE examen ADD CONSTRAINT examen_pk PRIMARY KEY ( examen_id );

CREATE TABLE historia_clinica (
    paciente_id     NUMBER NOT NULL,
    historia_id     NUMBER NOT NULL,
    numero_historia VARCHAR2(20) NOT NULL,
    fecha_apertura  DATE NOT NULL,
    grupo_sanguineo VARCHAR2(3),
    alergias        VARCHAR2(500),
    antecedentes    VARCHAR2(1000)
);

ALTER TABLE historia_clinica
    ADD
        CHECK ( grupo_sanguineo IN ( 'A+', 'A-', 'AB+', 'AB-', 'B+',
                                     'B-', 'O+', 'O-' ) );

CREATE UNIQUE INDEX historia_clinica__idx ON
    historia_clinica (
        paciente_id
    ASC );

ALTER TABLE historia_clinica ADD CONSTRAINT historia_clinica_pk PRIMARY KEY ( historia_id );

ALTER TABLE historia_clinica ADD CONSTRAINT historia_numero_un UNIQUE ( numero_historia );

ALTER TABLE historia_clinica ADD CONSTRAINT historia_paciente_un UNIQUE ( paciente_id );

CREATE TABLE hospitalizacion (
    hospitalizacion_id NUMBER NOT NULL,
    fecha_ingreso      DATE NOT NULL,
    fecha_egreso       DATE,
    motivo_ingreso     VARCHAR2(300) NOT NULL,
    estado             VARCHAR2(10) DEFAULT 'activa' NOT NULL,
    cama_id            NUMBER NOT NULL,
    atencion_id        NUMBER NOT NULL
);

ALTER TABLE hospitalizacion
    ADD CHECK ( estado IN ( 'activa', 'egresada' ) );

CREATE UNIQUE INDEX hospitalizacion__idx ON
    hospitalizacion (
        atencion_id
    ASC );

ALTER TABLE hospitalizacion ADD CONSTRAINT hospitalizacion_pk PRIMARY KEY ( hospitalizacion_id );

CREATE TABLE medicamento (
    medicamento_id     NUMBER NOT NULL,
    nombre_medicamento VARCHAR2(120) NOT NULL,
    presentacion       VARCHAR2(60) NOT NULL,
    concentracion      VARCHAR2(30),
    activo             VARCHAR2(1) DEFAULT 'S' NOT NULL
);

ALTER TABLE medicamento
    ADD CHECK ( activo IN ( 'N', 'S' ) );

ALTER TABLE medicamento ADD CONSTRAINT medicamento_pk PRIMARY KEY ( medicamento_id );

CREATE TABLE ordena (
    atencion_atencion_id NUMBER NOT NULL,
    examen_examen_id     NUMBER NOT NULL
);

ALTER TABLE ordena ADD CONSTRAINT ordena_pk PRIMARY KEY ( atencion_atencion_id,
                                                          examen_examen_id );

CREATE TABLE paciente (
    paciente_id      NUMBER NOT NULL,
    tipo_documento   VARCHAR2(2) NOT NULL,
    numero_documento VARCHAR2(20) NOT NULL,
    nombres          VARCHAR2(60) NOT NULL,
    apellidos        VARCHAR2(60) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo             VARCHAR2(1) NOT NULL,
    telefono         VARCHAR2(20),
    direccion        VARCHAR2(120)
);

ALTER TABLE paciente
    ADD
        CHECK ( tipo_documento IN ( 'CC', 'CE', 'PA', 'TI' ) );

ALTER TABLE paciente
    ADD
        CHECK ( sexo IN ( 'F', 'M', 'O' ) );

ALTER TABLE paciente ADD CONSTRAINT paciente_pk PRIMARY KEY ( paciente_id );

ALTER TABLE paciente ADD CONSTRAINT paciente_numero_documento_un UNIQUE ( numero_documento );

CREATE TABLE prescribe (
    atencion_atencion_id       NUMBER NOT NULL,
    medicamento_medicamento_id NUMBER NOT NULL
);

ALTER TABLE prescribe ADD CONSTRAINT prescribe_pk PRIMARY KEY ( atencion_atencion_id,
                                                                medicamento_medicamento_id );

ALTER TABLE atencion
    ADD CONSTRAINT atencion_historia_clinica_fk FOREIGN KEY ( historia_id )
        REFERENCES historia_clinica ( historia_id );

ALTER TABLE atiende
    ADD CONSTRAINT atiende_atencion_fk FOREIGN KEY ( atencion_atencion_id )
        REFERENCES atencion ( atencion_id );

ALTER TABLE atiende
    ADD CONSTRAINT atiende_doctor_fk FOREIGN KEY ( doctor_doctor_id )
        REFERENCES doctor ( doctor_id );

ALTER TABLE cama
    ADD CONSTRAINT cama_area_fk FOREIGN KEY ( area_id )
        REFERENCES area ( area_id );

ALTER TABLE diagnostica
    ADD CONSTRAINT diagnostica_atencion_fk FOREIGN KEY ( atencion_atencion_id )
        REFERENCES atencion ( atencion_id );

ALTER TABLE diagnostica
    ADD CONSTRAINT diagnostica_diagnostico_fk FOREIGN KEY ( diagnostico_diagnostico_id )
        REFERENCES diagnostico ( diagnostico_id );

ALTER TABLE doctor
    ADD CONSTRAINT doctor_especialidad_fk FOREIGN KEY ( especialidad_id )
        REFERENCES especialidad ( especialidad_id );

ALTER TABLE historia_clinica
    ADD CONSTRAINT historia_clinica_paciente_fk FOREIGN KEY ( paciente_id )
        REFERENCES paciente ( paciente_id );

ALTER TABLE hospitalizacion
    ADD CONSTRAINT hospitalizacion_atencion_fk FOREIGN KEY ( atencion_id )
        REFERENCES atencion ( atencion_id );

ALTER TABLE hospitalizacion
    ADD CONSTRAINT hospitalizacion_cama_fk FOREIGN KEY ( cama_id )
        REFERENCES cama ( cama_id );

ALTER TABLE ordena
    ADD CONSTRAINT ordena_atencion_fk FOREIGN KEY ( atencion_atencion_id )
        REFERENCES atencion ( atencion_id );

ALTER TABLE ordena
    ADD CONSTRAINT ordena_examen_fk FOREIGN KEY ( examen_examen_id )
        REFERENCES examen ( examen_id );

ALTER TABLE prescribe
    ADD CONSTRAINT prescribe_atencion_fk FOREIGN KEY ( atencion_atencion_id )
        REFERENCES atencion ( atencion_id );

ALTER TABLE prescribe
    ADD CONSTRAINT prescribe_medicamento_fk FOREIGN KEY ( medicamento_medicamento_id )
        REFERENCES medicamento ( medicamento_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             2
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
